M48
; DRILL file {KiCad 9.0.4} date 2026-01-14T14:58:24-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-14T14:58:24-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X2.091Y-5.595
X2.7Y-5.05
X3.25Y-5.05
X3.8Y-5.05
X4.409Y-5.595
T2
X1.6Y-1.6
X1.6Y-5.7
X8.7Y-1.6
X8.7Y-5.7
T3
X2.2Y-5.45
X4.3Y-5.45
M30
